export const LOGIN = {
    USER_LOGGING_IN: "SESSION.USER_LOGGING_IN",
    USER_LOGGED_IN: "SESSION.USER_LOGGED_IN",
    USER_LOGGED_OUT: "SESSION.USER_LOGGED_OUT"
};

export const APP = {
    TOGGLE_SIDEBAR: "APP.TOGGLE_SIDEBAR"
};

export const CUSTOMER = {
    CHANGE_CUSTOMER_PAGE: "CUSTOMER.CHANGE_CUSTOMER_PAGE",
    CUSTOMER_FORM_OPEN: "CUSTOMER.CUSTOMER_FORM_OPEN",
    CUSTOMER_FORM_CLOSE: "CUSTOMER.CUSTOMER_FORM_CLOSE",
    CUSTOMER_FORM_CHANGED: "CUSTOMER.CUSTOMER_FORM_CHANGED",
    SEARCH_CUSTOMERS: "CUSTOMER.SEARCH_CUSTOMERS"
};

export const SUPPLIER = {
    CHANGE_SUPPLIER_PAGE: "SUPPLIER.CHANGE_SUPPLIER_PAGE",
    SUPPLIER_FORM_OPEN: "SUPPLIER.SUPPLIER_FORM_OPEN",
    SUPPLIER_FORM_CLOSE: "SUPPLIER.SUPPLIER_FORM_CLOSE",
    SUPPLIER_FORM_CHANGED: "SUPPLIER.SUPPLIER_FORM_CHANGED",
    SEARCH_SUPPLIERS: "SUPPLIER.SEARCH_SUPPLIERS"
};

export const ITEM = {
    CHANGE_ITEM_PAGE: "ITEM.CHANGE_ITEM_PAGE",
    ITEM_FORM_OPEN: "ITEM.ITEM_FORM_OPEN",
    ITEM_FORM_CLOSE: "ITEM.ITEM_FORM_CLOSE",
    ITEM_FORM_CHANGED: "ITEM.ITEM_FORM_CHANGED",
    SEARCH_ITEMS: "ITEM.SEARCH_ITEMS",
    REFRESH_CATEGORIES: "ITEM.ITEM_REFRESH_CATEGORIES",
    REFRESH_BRANDS: "ITEM.ITEM_REFRESH_BRANDS",
    REFRESH_CATEGORIES_FAILED: "ITEM.ITEM_REFRESH_CATEGORIES_FAILED",
    REFRESH_BRANDS_FAILED: "ITEM.ITEM_REFRESH_BRANDS_FAILED"
};

export const CATEGORY = {
    CHANGE_CATEGORY_PAGE: "CATEGORY.CHANGE_CATEGORY_PAGE",
    CATEGORY_FORM_OPEN: "CATEGORY.CATEGORY_FORM_OPEN",
    CATEGORY_FORM_CLOSE: "CATEGORY.CATEGORY_FORM_CLOSE",
    CATEGORY_FORM_CHANGED: "CATEGORY.CATEGORY_FORM_CHANGED",
    SEARCH_CATEGORIES: "CATEGORY.SEARCH_CATEGORIES"
};

export const BRAND = {
    CHANGE_BRAND_PAGE: "BRAND.CHANGE_BRAND_PAGE",
    BRAND_FORM_OPEN: "BRAND.BRAND_FORM_OPEN",
    BRAND_FORM_CLOSE: "BRAND.BRAND_FORM_CLOSE",
    BRAND_FORM_CHANGED: "BRAND.BRAND_FORM_CHANGED",
    SEARCH_BRANDS: "BRAND.SEARCH_BRANDS"
};

export const ORDER = {
    CHANGE_ORDER_PAGE: "ORDER.CHANGE_ORDER_PAGE",
    ORDER_FORM_OPEN: "ORDER.ORDER_FORM_OPEN",
    ORDER_FORM_CLOSE: "ORDER.ORDER_FORM_CLOSE",
    ORDER_FORM_CHANGED: "ORDER.ORDER_FORM_CHANGED",
    ORDER_ITEM_FORM_OPEN: "ORDER.ORDER_ITEM_FORM_OPEN",
    ORDER_ITEM_FORM_CLOSE: "ORDER.ORDER_ITEM_FORM_CLOSE",
    ORDER_ITEM_FORM_CHANGED: "ORDER.ORDER_ITEM_FORM_CHANGED",
    SEARCH_ORDERS: "ORDER.SEARCH_ORDERS",
    REFRESH_CUSTOMERS: "ORDER.ORDER_REFRESH_CUSTOMERS",
    REFRESH_ITEMS: "ORDER.ORDER_REFRESH_ITEMS",
    REFRESH_CUSTOMERS_FAILED: "ORDER.ORDER_REFRESH_CUSTOMERS_FAILED",
    REFRESH_ITEMS_FAILED: "ORDER.ORDER_REFRESH_ITEMS_FAILED"
};

export const ITEM_ADJUSTMENT = {
    CHANGE_ITEM_ADJUSTMENT_PAGE: "ITEM_ADJUSTMENT.CHANGE_ITEM_ADJUSTMENT_PAGE",
    ITEM_ADJUSTMENT_FORM_OPEN: "ITEM_ADJUSTMENT.ITEM_ADJUSTMENT_FORM_OPEN",
    ITEM_ADJUSTMENT_FORM_CLOSE: "ITEM_ADJUSTMENT.ITEM_ADJUSTMENT_FORM_CLOSE",
    ITEM_ADJUSTMENT_FORM_CHANGED:
        "ITEM_ADJUSTMENT.ITEM_ADJUSTMENT_FORM_CHANGED",
    SEARCH_ITEM_ADJUSTMENTS: "ITEM_ADJUSTMENT.SEARCH_ITEM_ADJUSTMENTS",
    REFRESH_ITEMS: "ITEM_ADJUSTMENT.ITEM_ADJUSTMENT_REFRESH_ITEMS",
    REFRESH_ITEMS_FAILED: "ITEM_ADJUSTMENT.ITEM_ADJUSTMENT_REFRESH_ITEMS_FAILED"
};

export const SUPPLY_ORDER = {
    CHANGE_SUPPLY_ORDER_PAGE: "SUPPLY_ORDER.CHANGE_SUPPLY_ORDER_PAGE",
    SUPPLY_ORDER_FORM_OPEN: "SUPPLY_ORDER.SUPPLY_ORDER_FORM_OPEN",
    SUPPLY_ORDER_FORM_CLOSE: "SUPPLY_ORDER.SUPPLY_ORDER_FORM_CLOSE",
    SUPPLY_ORDER_FORM_CHANGED: "SUPPLY_ORDER.SUPPLY_ORDER_FORM_CHANGED",
    SEARCH_SUPPLY_ORDERS: "SUPPLY_ORDER.SEARCH_SUPPLY_ORDERS",
    REFRESH_ITEMS: "SUPPLY_ORDER.SUPPLY_ORDER_REFRESH_ITEMS",
    REFRESH_ITEMS_FAILED: "SUPPLY_ORDER.SUPPLY_ORDER_REFRESH_ITEMS_FAILED",
    REFRESH_SUPPLIERS: "SUPPLY_ORDER.SUPPLY_ORDER_REFRESH_SUPPLIERS",
    REFRESH_SUPPLIERS_FAILED:
        "SUPPLY_ORDER.SUPPLY_ORDER_REFRESH_SUPPLIERS_FAILED"
};

export const USER = {
    CHANGE_USER_PAGE: "USER.CHANGE_USER_PAGE",
    SEARCH_USERS: "USER.SEARCH_USERS"
};

export const SESSION = {
    OPEN_CHANGE_PASSWORD_FORM: "SESSION.OPEN_CHANGE_PASSWORD_FORM",
    CLOSE_CHANGE_PASSWORD_FORM: "SESSION.CLOSE_CHANGE_PASSWORD_FORM",
    PASSWORD_CHANGED: "SESSION.PASSWORD_CHANGED",
    LOGGED_IN: "SESSION.LOGGED_IN",
    LOGGED_OUT: "SESSION.LOGGED_OUT"
};
