export const LOGIN = {
    USER_LOGGING_IN: "SESSION/USER_LOGGING_IN",
    USER_LOGGED_IN: "SESSION/USER_LOGGED_IN",
    USER_LOGGED_OUT: "SESSION/USER_LOGGED_OUT"
};

export const APP = {
    TOGGLE_SIDEBAR: "APP/TOGGLE_SIDEBAR",
    SELECT_MENU: "SELECT_MENU",
    TOGGLE_USER_MENU: "TOGGLE_USER_MENU"
};

export const CUSTOMER = {
    CHANGE_CUSTOMER_PAGE: "CHANGE_CUSTOMER_PAGE",
    CUSTOMER_FORM_OPEN: "CUSTOMER_FORM_OPEN",
    CUSTOMER_FORM_CLOSE: "CUSTOMER_FORM_CLOSE",
    CUSTOMER_FORM_CHANGED: "CUSTOMER_FORM_CHANGED",
    SEARCH_CUSTOMERS: "SEARCH_CUSTOMERS"
};

export const SUPPLIER = {
    CHANGE_SUPPLIER_PAGE: "CHANGE_SUPPLIER_PAGE",
    SUPPLIER_FORM_OPEN: "SUPPLIER_FORM_OPEN",
    SUPPLIER_FORM_CLOSE: "SUPPLIER_FORM_CLOSE",
    SUPPLIER_FORM_CHANGED: "SUPPLIER_FORM_CHANGED",
    SEARCH_SUPPLIERS: "SEARCH_SUPPLIERS"
};

export const ITEM = {
    CHANGE_ITEM_PAGE: "CHANGE_ITEM_PAGE",
    ITEM_FORM_OPEN: "ITEM_FORM_OPEN",
    ITEM_FORM_CLOSE: "ITEM_FORM_CLOSE",
    ITEM_FORM_CHANGED: "ITEM_FORM_CHANGED",
    SEARCH_ITEMS: "SEARCH_ITEMS",
    REFRESH_CATEGORIES: "REFRESH_CATEGORIES",
    REFRESH_BRANDS: "REFRESH_BRANDS",
    REFRESH_CATEGORIES_FAILED: "REFRESH_CATEGORIES_FAILED",
    REFRESH_BRANDS_FAILED: "REFRESH_BRANDS_FAILED"
};

export const CATEGORY = {
    CHANGE_CATEGORY_PAGE: "CHANGE_CATEGORY_PAGE",
    CATEGORY_FORM_OPEN: "CATEGORY_FORM_OPEN",
    CATEGORY_FORM_CLOSE: "CATEGORY_FORM_CLOSE",
    CATEGORY_FORM_CHANGED: "CATEGORY_FORM_CHANGED",
    SEARCH_CATEGORIES: "SEARCH_CATEGORIES"
};

export const BRAND = {
    CHANGE_BRAND_PAGE: "CHANGE_BRAND_PAGE",
    BRAND_FORM_OPEN: "BRAND_FORM_OPEN",
    BRAND_FORM_CLOSE: "BRAND_FORM_CLOSE",
    BRAND_FORM_CHANGED: "BRAND_FORM_CHANGED",
    SEARCH_BRANDS: "SEARCH_BRANDS"
};

export const ORDER = {
    CHANGE_ORDER_PAGE: "CHANGE_ORDER_PAGE",
    REFRESH_ORDER_LIST_BEGIN: "REFRESH_ORDER_LIST_BEGIN",
    REFRESH_ORDER_LIST_FINISHED: "REFRESH_ORDER_LIST_FINISHED",
    REFRESH_ORDER_LIST_FAILED: "REFRESH_ORDER_LIST_FAILED",
    ORDER_FORM_OPEN: "ORDER_FORM_OPEN",
    ORDER_FORM_CLOSE: "ORDER_FORM_CLOSE",
    ORDER_FORM_CHANGED: "ORDER_FORM_CHANGED",
    ORDER_ITEM_FORM_OPEN: "ORDER_ITEM_FORM_OPEN",
    ORDER_ITEM_FORM_CLOSE: "ORDER_ITEM_FORM_CLOSE",
    ORDER_ITEM_FORM_CHANGED: "ORDER_ITEM_FORM_CHANGED",
    ORDER_ITEM_ADDED: "ORDER_ITEM_ADDED",
    ORDER_ITEM_CHANGED: "ORDER_ITEM_CHANGED",
    ORDER_ITEM_REMOVED: "ORDER_ITEM_REMOVED",
    SEARCH_ORDERS: "SEARCH_ORDERS",
    REFRESH_CUSTOMERS: "REFRESH_CUSTOMERS",
    REFRESH_ITEMS: "REFRESH_ITEMS",
    REFRESH_CUSTOMERS_FAILED: "REFRESH_CUSTOMERS_FAILED",
    REFRESH_ITEMS_FAILED: "REFRESH_ITEMS_FAILED"
};
