const LOGIN = {
    USER_LOGGING_IN: "SESSION/USER_LOGGING_IN",
    USER_LOGGED_IN: "SESSION/USER_LOGGED_IN",
    USER_LOGGED_OUT: "SESSION/USER_LOGGED_OUT"
};

const APP = {
    TOGGLE_SIDEBAR: "APP/TOGGLE_SIDEBAR",
    SELECT_MENU: "SELECT_MENU",
    TOGGLE_USER_MENU: "TOGGLE_USER_MENU"
};

const CUSTOMER = {
    CHANGE_CUSTOMERS_PAGE: "CHANGE_CUSTOMERS_PAGE",
    REFRESH_CUSTOMER_LIST_BEGIN: "REFRESH_CUSTOMER_LIST_BEGIN",
    REFRESH_CUSTOMER_LIST_FINISHED: "REFRESH_CUSTOMER_LIST_FINISHED",
    REFRESH_CUSTOMER_LIST_FAILED: "REFRESH_CUSTOMER_LIST_FAILED",
    CUSTOMER_FORM_OPEN: "CUSTOMER_FORM_OPEN",
    CUSTOMER_FORM_CLOSE: "CUSTOMER_FORM_CLOSE",
    SEARCH_CUSTOMERS: "SEARCH_CUSTOMERS",
    DELETE_CUSTOMER: "DELETE_CUSTOMER"
};

const SUPPLIER = {
    CHANGE_SUPPLIER_PAGE: "CHANGE_SUPPLIER_PAGE",
    SUPPLIER_FORM_OPEN: "SUPPLIER_FORM_OPEN",
    SUPPLIER_FORM_CLOSE: "SUPPLIER_FORM_CLOSE",
    SUPPLIER_FORM_CHANGED: "SUPPLIER_FORM_CHANGED",
    SEARCH_SUPPLIERS: "SEARCH_SUPPLIERS"
};

const INVENTORY = {
    CHANGE_INVENTORY_PAGE: "CHANGE_INVENTORY_PAGE",
    INVENTORY_FORM_OPEN: "INVENTORY_FORM_OPEN",
    INVENTORY_FORM_CLOSE: "INVENTORY_FORM_CLOSE",
    INVENTORY_FORM_CHANGED: "INVENTORY_FORM_CHANGED",
    SEARCH_INVENTORIES: "SEARCH_INVENTORIES",
    REFRESH_CATEGORIES: "REFRESH_CATEGORIES",
    REFRESH_CATEGORIES_FAILED: "REFRESH_CATEGORIES_FAILED"
};

const CATEGORY = {
    CHANGE_CATEGORY_PAGE: "CHANGE_CATEGORY_PAGE",
    CATEGORY_FORM_OPEN: "CATEGORY_FORM_OPEN",
    CATEGORY_FORM_CLOSE: "CATEGORY_FORM_CLOSE",
    CATEGORY_FORM_CHANGED: "CATEGORY_FORM_CHANGED",
    SEARCH_CATEGORIES: "SEARCH_CATEGORIES"
};

const INVOICE = {
    CHANGE_INVOICE_PAGE: "CHANGE_INVOICE_PAGE",
    REFRESH_INVOICE_LIST_BEGIN: "REFRESH_INVOICE_LIST_BEGIN",
    REFRESH_INVOICE_LIST_FINISHED: "REFRESH_INVOICE_LIST_FINISHED",
    REFRESH_INVOICE_LIST_FAILED: "REFRESH_INVOICE_LIST_FAILED",
    INVOICE_FORM_OPEN: "INVOICE_FORM_OPEN",
    INVOICE_FORM_CLOSE: "INVOICE_FORM_CLOSE",
    SEARCH_INVOICES: "SEARCH_INVOICES",
    DELETE_INVOICE: "DELETE_INVOICE"
};

const RECORDSTATUS = {
    ACTIVE: 0,
    INACTIVE: 1,
    DELETED: 2
};

export {
    LOGIN,
    APP,
    CUSTOMER,
    INVOICE,
    INVENTORY,
    CATEGORY,
    SUPPLIER,
    RECORDSTATUS
};
